version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: latest
    commands:
      - python -V
      - node --version
  build:
    commands:
      - pwd
      - ls -l
      - echo ${AWS_DEFAULT_REGION}
      - echo ${AWS_REGION}
      - echo ${CODEBUILD_BATCH_BUILD_IDENTIFIER}
      - echo ${CODEBUILD_BUILD_ARN}
      - echo ${CODEBUILD_BUILD_ID}
      - echo ${CODEBUILD_BUILD_IMAGE}
      - echo ${CODEBUILD_BUILD_NUMBER}
      - echo ${CODEBUILD_BUILD_SUCCEEDING}
      - echo ${CODEBUILD_INITIATOR}
      - echo ${CODEBUILD_KMS_KEY_ID}
      - echo ${CODEBUILD_LOG_PATH}
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo ${CODEBUILD_SOURCE_REPO_URL}
      - echo ${CODEBUILD_SOURCE_VERSION}
      - echo ${CODEBUILD_SRC_DIR}
      - echo ${CODEBUILD_START_TIME}
      - echo ${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID}
      - echo ${CODEBUILD_WEBHOOK_BASE_REF}
      - echo ${CODEBUILD_WEBHOOK_EVENT}
      - echo ${CODEBUILD_WEBHOOK_HEAD_REF}
      - echo ${CODEBUILD_WEBHOOK_MERGE_COMMIT}
      - echo ${CODEBUILD_WEBHOOK_PREV_COMMIT}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - echo ${HOME}
      - touch $CODEBUILD_BUILD_NUMBER.output
artifacts:
  files:
    - "**/*"
  name: aws-code-cicd-poc-$CODEBUILD_BUILD_NUMBER
