version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: latest
    commands:
      - python -V
      - node --version
  build:
    commands:
      - echo "PREPROD DEPLOY"
  artifacts:
    files:
      - "**/*"
    name: aws-code-cicd-poc-$CODEBUILD_BUILD_NUMBER
