version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: latest
    commands:
      - python -V
      - node --version
  build:
    commands:
      - echo "PREPROD DEPLOY"
