version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - python -V
      - node --version
  build:
    commands:
      - pwd
      - ls -l
      - python -V
      - node --version
